- name: Docker launch container
  hosts: all
  tasks:
    - name: Create a data container
        community.docker.docker_container:
          name: my-ghost
          image: ghost
          state: started
          ports: 
            - "3001:2368"
          env:
            url: "http://{{ ansible_ssh_host }}:3001"
          

